### ISSUE TITLE
能不能自定义域名和选择GPT模型，这样我可以使用三方的域名和key了，还能用GPT4

### ISSUE THREAD

**Issue by Xu-Jam** [yimingsun12138/ChatGPT4R-CN#1]

**Comment by yimingsun12138** [comment]
1.支持自选GPT模型，只要是`OpenAI_model_list()`函数返回的模型你都可以选择，例如选择最新的GPT4模型：
`chat <- Init_chat_session(model = 'gpt-4-0314')`。

2.key本来就是使用你自己OpenAI账号的token。

3.暂时不考虑自定义域名。因为我不确定第三方域名会不会对OpenAI官方api的返回内容作修改，导致兼容性上的问题；其次，我认为我的反向代理方案在可用性和安全性上已经足够好了，所以我暂时不会考虑添加自定义域名。当然，你完全可以folk一下我的repo，然后在`R/API_URL.R`中修改成你的自定义域名即可。

**Comment by Xu-Jam** [comment]
好的，谢谢
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Yiming ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月22日 18:38
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [yimingsun12138/ChatGPT4R-CN] 能不能自定义域名和选择GPT模型，这样我可以使用三方的域名和key了，还能用GPT4 (Issue #1)
        
      
    
  

1.支持自选GPT模型，只要是OpenAI_model_list()函数返回的模型你都可以选择，例如选择最新的GPT4模型：
chat <- Init_chat_session(model = 'gpt-4-0314')。
2.key本来就是使用你自己OpenAI账号的token。
3.暂时不考虑自定义域名。因为我不确定第三方域名会不会对OpenAI官方api的返回内容作修改，导致兼容性上的问题；其次，我认为我的反向代理方案在可用性和安全性上已经足够好了，所以我暂时不会考虑添加自定义域名。当然，你完全可以folk一下我的repo，然后在R/API_URL.R中修改成你的自定义域名即可。
