### ISSUE TITLE
大佬您好，我这装不上。。。

### ISSUE THREAD

**Issue by Xu-Jam** [yimingsun12138/ChatGPT4R-CN#2]
> devtools::install_github('yimingsun12138/ChatGPT4R-CN')
Error: Failed to install 'unknown package' from GitHub:
  schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by yimingsun12138** [comment]
搜了一下这个报错，是网络问题：
https://blog.csdn.net/yuanzhoulvpi/article/details/104796859
国内连不上GitHub很正常，
可能的解决方案：
1. 换个时间多试几次
2. 尝试全局代理
3. 下载源码压缩成tar.gz后直接`install.packages`进行安装

**Comment by Xu-Jam** [comment]
好
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Yiming ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月25日 16:51
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [yimingsun12138/ChatGPT4R-CN] 大佬您好，我这装不上。。。 (Issue #2)
        
      
    
  

搜了一下这个报错，是网络问题：
https://blog.csdn.net/yuanzhoulvpi/article/details/104796859
国内连不上GitHub很正常，
可能的解决方案：

换个时间多试几次
尝试全局代理
下载源码压缩成tar.gz后直接install.packages进行安装
