### ISSUE TITLE
大佬，我可以在其它地方用一下你的反代域名吗？仅个人使用

### ISSUE THREAD

**Issue by Xu-Jam** [yimingsun12138/ChatGPT4R-CN#3]

**Comment by yimingsun12138** [comment]
当然可以，欢迎使用

**Comment by Xu-Jam** [comment]
感谢！
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Yiming ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月6日 10:58
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [yimingsun12138/ChatGPT4R-CN] 大佬，我可以在其它地方用一下你的反代域名吗？仅个人使用 (Issue #3)
        
      
    
  

当然可以，欢迎使用
